
services:
  ros-gazebo:
    build: ./
    container_name: ros-gazebo
    network_mode: host
    stdin_open: true  # Keep stdin open for interaction
    tty: true   
    environment:
      - "XAUTHORITYS"
      - "DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/aerial_manipulator:/home/aerial_manipulator_ws/:rw
      - ~/src/PX4-Autopilot:/src/PX4-Autopilot/:rw
    devices:
      - "/dev/dri/"
    command: bash src/autorun.sh